export const MY_RIDES_PAGE_INITIAL_WIDTH = 375;
export const MY_RIDES_PAGE_INITIAL_HEIGHT = 667;
export const MY_RIDES_PAGE_BACKGROUND_INITIAL_WIDTH = 487;

export const MY_RIDES_PAGE_BACKGROUND_INITIAL_HEIGHT = 374;
export const MY_RIDES_PAGE_BACKGROUND_INITIAL_POSITION_TOP = 45;
export const MY_RIDES_PAGE_BACKGROUND_INITIAL_POSITION_LEFT = -112;
export const MY_RIDES_PAGE_CONTENT_INITIAL_HEIGHT = 207;
export const MY_RIDES_PAGE_CONTENT_MAX_WIDTH = 223;
